# Adds blobstore benchmark errand for s3 storage-cli

- type: replace
  path: /instance_groups/-
  value:
    name: blobstore-benchmark-storage-cli
    instances: 1
    azs: [z1]
    networks:
      - name: default
    vm_type: default
    stemcell: default
    lifecycle: errand
    jobs:
      - name: blobstore_benchmark
        release: capi
        properties:
          blobstore_benchmark:
            mode: storage-cli
            cc_overrides:
              db_logging_level: error
              logging_level: error
              log_db_queries: false
              db:
                log_level: error
                log_db_queries: false
              blobstore_type: storage-cli
              buildpacks:
                blobstore_type: storage-cli
                blobstore_provider: AWS
                connection_config:
                  aws_secret_access_key: ((blobstore_secret_access_key))
                  aws_access_key_id: ((blobstore_access_key_id))
                  bucket_name: ((buildpack_directory_key))
                  provider: AWS
              droplets:
                blobstore_type: storage-cli
                blobstore_provider: AWS
                connection_config:
                  aws_secret_access_key: ((blobstore_secret_access_key))
                  aws_access_key_id: ((blobstore_access_key_id))
                  bucket_name: ((droplet_directory_key))
                  provider: AWS
              packages:
                blobstore_type: storage-cli
                blobstore_provider: AWS
                connection_config:
                  aws_secret_access_key: ((blobstore_secret_access_key))
                  aws_access_key_id: ((blobstore_access_key_id))
                  bucket_name: ((app_package_directory_key))
                  provider: AWS
              resource_pool:
                blobstore_type: storage-cli
                blobstore_provider: AWS
                connection_config:
                  aws_secret_access_key: ((blobstore_secret_access_key))
                  aws_access_key_id: ((blobstore_access_key_id))
                  bucket_name: ((resource_directory_key))
                  provider: AWS